# Generated by Django 6.0.3 on 2026-03-11 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_created_at_profile_favourites_and_more'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
