# Generated by Django 6.0.3 on 2026-03-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_user"),
        ("restaurants", "0002_recommendation_profile_review_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="disliked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_recommendations",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_recommendations", to="profiles.profile"
            ),
        ),
    ]
