# Generated by Django 6.0.3 on 2026-04-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_recommendation_disliked_by_recommendation_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
