# Generated by Django 6.0.3 on 2026-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0003_recommendation_disliked_by_recommendation_liked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="restaurant_reply",
            field=models.TextField(blank=True, null=True),
        ),
    ]
