# Generated by Django 6.0.3 on 2026-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_review_restaurant_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='dietary_restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
