# Generated by Django 6.0.3 on 2026-04-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_add_tags_to_review'),
        ('restaurants', '0005_restaurant_allergens_restaurant_dietary_restrictions'),
    ]

    operations = [
    ]
