# Generated by Django 6.0.3 on 2026-04-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_review_is_reported_review_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='other_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
