# Generated by Django 6.0.3 on 2026-04-03 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_profile_user"),
        ("restaurants", "0003_recommendation_disliked_by_recommendation_liked_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profile",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_student", True)),
                fields=("university", "student_id"),
                name="unique_university_student_id_when_student",
            ),
        ),
    ]
