# Generated by Django 6.0.3 on 2026-04-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_unique_together_and_more"),
        ("restaurants", "0004_review_restaurant_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="works_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="employees",
                to="restaurants.restaurant",
            ),
        ),
    ]
