# Generated by Django 6.0.3 on 2026-04-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_profile_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
