# Generated by Django 6.0.3 on 2026-04-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_alter_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
