# Generated by Django 6.0.3 on 2026-04-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_works_for"),
        ("profiles", "0007_alter_profile_image_url"),
    ]

    operations = []
