# Generated by Django 6.0.3 on 2026-04-09 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_merge_20260404_2129"),
        ("restaurants", "0008_restaurant_other_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="works_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="restaurants.restaurant",
            ),
        ),
    ]
