from django.core.management.base import BaseCommand
from restaurants.models import Restaurant


class Command(BaseCommand):
    help = "Seed the database with University of Calgary restaurants"

    def handle(self, *args, **kwargs):
        Restaurant.objects.all().delete()

        restaurants = [
            {
                "name": "A&W",
                "description": "Fast food chain serving burgers, fries, breakfast items, and root beer.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Teen Burger", "price": 8.99},
                    {"name": "Mama Burger", "price": 6.49},
                    {"name": "Mozza Burger", "price": 8.79},
                    {"name": "Beyond Meat Burger", "price": 9.29},
                    {"name": "Chicken Burger", "price": 7.49},
                    {"name": "Fries", "price": 3.49},
                    {"name": "Onion Rings", "price": 3.99},
                    {"name": "Poutine", "price": 5.99},
                    {"name": "Breakfast Wrap", "price": 5.99},
                    {"name": "Root Beer Float", "price": 4.49}
                ],
                "min_price": 3.49,
                "max_price": 9.29,
                "days_of_operation": "Daily",
                "opening_hours": "09:00",
                "closing_hours": "20:00",
                "rating": 4.0
            },
            {
                "name": "Bake Chef Co.",
                "description": "Popular campus spot serving Asian-style sandwiches, bowls, and quick meals.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Beef Sub", "price": 7.99},
                    {"name": "Chicken Sub", "price": 7.49},
                    {"name": "BBQ Pork Sub", "price": 7.99},
                    {"name": "Spicy Chicken Sub", "price": 7.99},
                    {"name": "Rice Bowl", "price": 8.99},
                    {"name": "Teriyaki Chicken Bowl", "price": 9.49},
                    {"name": "Teriyaki Beef Bowl", "price": 9.99},
                    {"name": "Fried Rice", "price": 8.49},
                    {"name": "Spring Rolls", "price": 4.99},
                    {"name": "Beef Noodle Bowl", "price": 9.99}
                ],
                "min_price": 4.99,
                "max_price": 9.99,
                "days_of_operation": "Mon-Fri",
                "opening_hours": "10:00",
                "closing_hours": "17:00",
                "rating": 4.5
            },
            {
                "name": "Canadian Pizza Unlimited",
                "description": "Pizza counter serving slices, whole pizzas, and sides.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Pepperoni Slice", "price": 4.99},
                    {"name": "Cheese Slice", "price": 4.79},
                    {"name": "Veggie Slice", "price": 5.29},
                    {"name": "Cheese Pizza", "price": 11.99},
                    {"name": "Pepperoni Pizza", "price": 12.99},
                    {"name": "Hawaiian Pizza", "price": 13.49},
                    {"name": "BBQ Chicken Pizza", "price": 13.99},
                    {"name": "Meat Lovers Pizza", "price": 14.99},
                    {"name": "Wings", "price": 8.99},
                    {"name": "Garlic Bread", "price": 4.99}
                ],
                "min_price": 4.79,
                "max_price": 14.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "21:00",
                "rating": 3.8
            },
            {
                "name": "Carl's Jr.",
                "description": "American burger chain known for charbroiled burgers and fries.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Famous Star Burger", "price": 8.99},
                    {"name": "Western Bacon Cheeseburger", "price": 9.49},
                    {"name": "Double Cheeseburger", "price": 8.99},
                    {"name": "Chicken Sandwich", "price": 7.99},
                    {"name": "Spicy Chicken Burger", "price": 8.49},
                    {"name": "Chicken Tenders", "price": 7.99},
                    {"name": "Fries", "price": 3.49},
                    {"name": "Loaded Fries", "price": 5.99},
                    {"name": "Onion Rings", "price": 4.49},
                    {"name": "Milkshake", "price": 4.99}
                ],
                "min_price": 3.49,
                "max_price": 9.49,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "20:00",
                "rating": 4.0
            },
            {
                "name": "Chaiiwala of London",
                "description": "Cafe serving chai, wraps, and Indian street-food style snacks.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Karak Chai", "price": 3.99},
                    {"name": "Masala Chai", "price": 3.99},
                    {"name": "Samosa", "price": 2.99},
                    {"name": "Pakoras", "price": 4.99},
                    {"name": "Chicken Wrap", "price": 7.99},
                    {"name": "Butter Chicken Wrap", "price": 8.49},
                    {"name": "Paneer Wrap", "price": 7.49},
                    {"name": "Chicken Tikka Roll", "price": 8.49},
                    {"name": "Mango Lassi", "price": 4.99},
                    {"name": "Aloo Paratha", "price": 6.49}
                ],
                "min_price": 2.99,
                "max_price": 8.49,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "19:00",
                "rating": 4.2
            },
            {
                "name": "Coffee Company",
                "description": "Campus coffee kiosk serving hot drinks, pastries, and snacks.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Latte", "price": 4.25},
                    {"name": "Cappuccino", "price": 4.25},
                    {"name": "Americano", "price": 3.50},
                    {"name": "Espresso", "price": 2.99},
                    {"name": "Flat White", "price": 4.50},
                    {"name": "Iced Coffee", "price": 3.99},
                    {"name": "Muffin", "price": 3.25},
                    {"name": "Croissant", "price": 3.99},
                    {"name": "Bagel with Cream Cheese", "price": 3.75},
                    {"name": "Chocolate Chip Cookie", "price": 2.99}
                ],
                "min_price": 2.99,
                "max_price": 4.50,
                "days_of_operation": "Mon-Fri",
                "opening_hours": "08:00",
                "closing_hours": "16:00",
                "rating": 3.7
            },
            {
                "name": "Dairy Queen/Orange Julius",
                "description": "Ice cream and fast food chain with frozen drinks, burgers, and desserts.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Blizzard", "price": 5.99},
                    {"name": "Orange Julius", "price": 4.99},
                    {"name": "Strawberry Julius", "price": 4.99},
                    {"name": "Cheeseburger", "price": 6.99},
                    {"name": "Chicken Strips", "price": 8.99},
                    {"name": "Chicken Sandwich", "price": 7.99},
                    {"name": "Fries", "price": 3.49},
                    {"name": "Hot Dog", "price": 4.99},
                    {"name": "Chocolate Sundae", "price": 4.49},
                    {"name": "Banana Split", "price": 5.49}
                ],
                "min_price": 3.49,
                "max_price": 8.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "20:00",
                "rating": 4.0
            },
            {
                "name": "The Den & Black Lounge",
                "description": "Campus pub and lounge serving casual meals and snacks.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Classic Burger", "price": 12.99},
                    {"name": "Chicken Wings", "price": 11.99},
                    {"name": "Nachos", "price": 10.99},
                    {"name": "Chicken Tenders", "price": 10.49},
                    {"name": "Poutine", "price": 7.99},
                    {"name": "Clubhouse Sandwich", "price": 11.99},
                    {"name": "Caesar Salad", "price": 8.99},
                    {"name": "Loaded Fries", "price": 8.49},
                    {"name": "Buffalo Chicken Wrap", "price": 11.49},
                    {"name": "Fish and Chips", "price": 13.99}
                ],
                "min_price": 7.99,
                "max_price": 13.99,
                "days_of_operation": "Daily",
                "opening_hours": "11:00",
                "closing_hours": "23:00",
                "rating": 4.0
            },
            {
                "name": "Freshco Poke",
                "description": "Poke bowl spot serving seafood, chicken, tofu, and fresh toppings.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Salmon Poke Bowl", "price": 13.99},
                    {"name": "Tuna Poke Bowl", "price": 14.99},
                    {"name": "Veggie Bowl", "price": 11.99},
                    {"name": "Spicy Salmon Bowl", "price": 14.49},
                    {"name": "Chicken Poke Bowl", "price": 12.99},
                    {"name": "Shrimp Poke Bowl", "price": 13.99},
                    {"name": "Tofu Poke Bowl", "price": 11.99},
                    {"name": "Avocado Bowl", "price": 12.49},
                    {"name": "Seaweed Salad", "price": 5.99},
                    {"name": "Miso Soup", "price": 3.99}
                ],
                "min_price": 3.99,
                "max_price": 14.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.5
            },
            {
                "name": "Jugo Juice",
                "description": "Juice and smoothie bar with bowls, wraps, and healthy snacks.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Strawberry Banana Smoothie", "price": 6.99},
                    {"name": "Mango Magic Smoothie", "price": 6.99},
                    {"name": "Protein Smoothie", "price": 7.99},
                    {"name": "Berry Blast Smoothie", "price": 6.99},
                    {"name": "Green Smoothie", "price": 7.49},
                    {"name": "Acai Bowl", "price": 8.99},
                    {"name": "Peanut Butter Banana Smoothie", "price": 7.49},
                    {"name": "Orange Juice", "price": 4.99},
                    {"name": "Protein Wrap", "price": 8.49},
                    {"name": "Granola Yogurt Cup", "price": 5.99}
                ],
                "min_price": 4.99,
                "max_price": 8.99,
                "days_of_operation": "Daily",
                "opening_hours": "09:00",
                "closing_hours": "18:00",
                "rating": 4.0
            },
            {
                "name": "Kobe Beef",
                "description": "Japanese grill spot serving teriyaki bowls, tempura, and bento-style meals.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Teriyaki Chicken Bowl", "price": 11.99},
                    {"name": "Beef Teriyaki Bowl", "price": 12.99},
                    {"name": "Tempura", "price": 8.99},
                    {"name": "Chicken Bento", "price": 13.49},
                    {"name": "Beef Bento", "price": 13.99},
                    {"name": "Yakisoba", "price": 10.99},
                    {"name": "Chicken Katsu", "price": 12.49},
                    {"name": "Rice Bowl", "price": 9.99},
                    {"name": "Miso Soup", "price": 2.99},
                    {"name": "Gyoza", "price": 5.99}
                ],
                "min_price": 2.99,
                "max_price": 13.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.1
            },
            {
                "name": "Korean BBQ",
                "description": "Korean eatery serving BBQ plates, bowls, and rice dishes.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Bibimbap", "price": 11.99},
                    {"name": "Korean BBQ Chicken", "price": 12.99},
                    {"name": "Kimchi Fried Rice", "price": 10.99},
                    {"name": "Bulgogi Bowl", "price": 12.99},
                    {"name": "Spicy Pork Bowl", "price": 12.49},
                    {"name": "Japchae", "price": 10.99},
                    {"name": "Fried Dumplings", "price": 5.99},
                    {"name": "Rice Cake Plate", "price": 9.99},
                    {"name": "Miso Soup", "price": 2.99},
                    {"name": "Tofu Bibimbap", "price": 11.49}
                ],
                "min_price": 2.99,
                "max_price": 12.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.2
            },
            {
                "name": "La Fe Dim Sum",
                "description": "Dim sum counter serving dumplings, buns, and noodle dishes.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Pork Dumplings", "price": 7.99},
                    {"name": "Shrimp Dumplings", "price": 8.99},
                    {"name": "BBQ Pork Buns", "price": 6.99},
                    {"name": "Steamed Rice Roll", "price": 7.49},
                    {"name": "Spring Rolls", "price": 4.99},
                    {"name": "Wonton Soup", "price": 6.49},
                    {"name": "Beef Noodle Bowl", "price": 9.99},
                    {"name": "Chicken Fried Rice", "price": 8.99},
                    {"name": "Sesame Balls", "price": 4.49},
                    {"name": "Vegetable Dumplings", "price": 7.49}
                ],
                "min_price": 4.49,
                "max_price": 9.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.0
            },
            {
                "name": "Last Defence Lounge",
                "description": "Casual campus lounge serving pub-style meals and appetizers.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Nachos", "price": 11.99},
                    {"name": "Chicken Wings", "price": 12.99},
                    {"name": "Burger", "price": 13.99},
                    {"name": "Chicken Tenders", "price": 10.99},
                    {"name": "Poutine", "price": 7.99},
                    {"name": "Mozzarella Sticks", "price": 8.49},
                    {"name": "Buffalo Wrap", "price": 11.49},
                    {"name": "Caesar Salad", "price": 8.99},
                    {"name": "Loaded Nacho Fries", "price": 9.49},
                    {"name": "Fish Tacos", "price": 12.49}
                ],
                "min_price": 7.99,
                "max_price": 13.99,
                "days_of_operation": "Daily",
                "opening_hours": "12:00",
                "closing_hours": "23:00",
                "rating": 3.9
            },
            {
                "name": "Mr. Pretzels",
                "description": "Snack kiosk specializing in pretzels, dips, and bite-sized treats.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Classic Pretzel", "price": 4.49},
                    {"name": "Cinnamon Pretzel", "price": 4.99},
                    {"name": "Pretzel Bites", "price": 5.49},
                    {"name": "Cheese Pretzel", "price": 5.29},
                    {"name": "Garlic Pretzel", "price": 5.29},
                    {"name": "Jalapeno Pretzel", "price": 5.49},
                    {"name": "Chocolate Pretzel", "price": 5.49},
                    {"name": "Cheese Dip", "price": 1.49},
                    {"name": "Caramel Dip", "price": 1.49},
                    {"name": "Pretzel Dog", "price": 6.49}
                ],
                "min_price": 1.49,
                "max_price": 6.49,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "19:00",
                "rating": 4.1
            },
            {
                "name": "Noodle and Grill Express",
                "description": "Asian fast-casual counter serving noodles, stir-fries, and rice plates.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Chicken Chow Mein", "price": 10.99},
                    {"name": "Beef Stir Fry", "price": 11.99},
                    {"name": "Vegetable Noodles", "price": 9.99},
                    {"name": "Teriyaki Chicken Plate", "price": 11.49},
                    {"name": "Beef Fried Rice", "price": 10.99},
                    {"name": "Sweet and Sour Chicken", "price": 11.49},
                    {"name": "Spicy Noodle Bowl", "price": 10.49},
                    {"name": "Spring Rolls", "price": 4.99},
                    {"name": "Egg Fried Rice", "price": 9.49},
                    {"name": "Chicken Rice Bowl", "price": 10.99}
                ],
                "min_price": 4.99,
                "max_price": 11.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.0
            },
            {
                "name": "OPA! of Greece",
                "description": "Mediterranean fast-casual spot serving wraps, platters, and salads.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Chicken Gyro", "price": 9.99},
                    {"name": "Lamb Platter", "price": 12.99},
                    {"name": "Greek Salad", "price": 6.99},
                    {"name": "Beef Gyro", "price": 10.49},
                    {"name": "Falafel Wrap", "price": 8.99},
                    {"name": "Chicken Platter", "price": 12.49},
                    {"name": "Hummus and Pita", "price": 5.99},
                    {"name": "Spanakopita", "price": 4.99},
                    {"name": "Rice Bowl", "price": 9.99},
                    {"name": "Baklava", "price": 4.49}
                ],
                "min_price": 4.49,
                "max_price": 12.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "20:00",
                "rating": 4.2
            },
            {
                "name": "Starbucks",
                "description": "Global coffee chain serving espresso drinks, refreshers, and pastries.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Latte", "price": 5.25},
                    {"name": "Caramel Macchiato", "price": 5.75},
                    {"name": "Cold Brew", "price": 4.95},
                    {"name": "Cappuccino", "price": 5.25},
                    {"name": "Mocha", "price": 5.75},
                    {"name": "Flat White", "price": 5.50},
                    {"name": "Frappuccino", "price": 6.25},
                    {"name": "Blueberry Muffin", "price": 3.95},
                    {"name": "Croissant", "price": 3.95},
                    {"name": "Iced Latte", "price": 5.25}
                ],
                "min_price": 3.95,
                "max_price": 6.25,
                "days_of_operation": "Daily",
                "opening_hours": "07:00",
                "closing_hours": "21:00",
                "rating": 4.3
            },
            {
                "name": "Stör",
                "description": "Campus convenience spot with packaged snacks, drinks, and grab-and-go items.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Turkey Sandwich", "price": 6.99},
                    {"name": "Veggie Wrap", "price": 6.49},
                    {"name": "Energy Drink", "price": 3.99},
                    {"name": "Bottled Juice", "price": 3.49},
                    {"name": "Chips", "price": 2.99},
                    {"name": "Granola Bar", "price": 1.99},
                    {"name": "Fruit Cup", "price": 4.49},
                    {"name": "Yogurt Parfait", "price": 4.99},
                    {"name": "Chicken Caesar Wrap", "price": 7.49},
                    {"name": "Chocolate Bar", "price": 2.49}
                ],
                "min_price": 1.99,
                "max_price": 7.49,
                "days_of_operation": "Daily",
                "opening_hours": "08:00",
                "closing_hours": "22:00",
                "rating": 3.8
            },
            {
                "name": "Subway",
                "description": "Sandwich chain with customizable subs, wraps, and cookies.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Turkey Sub", "price": 8.99},
                    {"name": "Veggie Delite", "price": 7.49},
                    {"name": "Italian BMT", "price": 9.49},
                    {"name": "Chicken Teriyaki Sub", "price": 9.49},
                    {"name": "Steak and Cheese Sub", "price": 10.49},
                    {"name": "Tuna Sub", "price": 8.99},
                    {"name": "Meatball Marinara", "price": 8.49},
                    {"name": "Chicken Bacon Ranch", "price": 10.99},
                    {"name": "Veggie Wrap", "price": 7.99},
                    {"name": "Cookies", "price": 1.99}
                ],
                "min_price": 1.99,
                "max_price": 10.99,
                "days_of_operation": "Daily",
                "opening_hours": "09:00",
                "closing_hours": "20:00",
                "rating": 3.9
            },
            {
                "name": "Tim Hortons",
                "description": "Canadian coffee chain with donuts, breakfast, and sandwiches.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Double Double Coffee", "price": 2.49},
                    {"name": "Breakfast Sandwich", "price": 4.99},
                    {"name": "Donut", "price": 1.79},
                    {"name": "Iced Capp", "price": 3.49},
                    {"name": "Bagel", "price": 2.49},
                    {"name": "Grilled Panini", "price": 6.99},
                    {"name": "Timbits", "price": 2.99},
                    {"name": "Latte", "price": 3.99},
                    {"name": "Soup", "price": 4.99},
                    {"name": "Farmers Wrap", "price": 5.49}
                ],
                "min_price": 1.79,
                "max_price": 6.99,
                "days_of_operation": "Daily",
                "opening_hours": "07:00",
                "closing_hours": "21:00",
                "rating": 3.8
            },
            {
                "name": "Tim Hortons Express",
                "description": "Smaller Tim Hortons kiosk with quick coffee and baked goods.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Coffee", "price": 2.29},
                    {"name": "Tea", "price": 2.19},
                    {"name": "Latte", "price": 3.89},
                    {"name": "Donut", "price": 1.79},
                    {"name": "Muffin", "price": 2.49},
                    {"name": "Bagel", "price": 2.49},
                    {"name": "Croissant", "price": 2.79},
                    {"name": "Breakfast Wrap", "price": 4.99},
                    {"name": "Iced Capp", "price": 3.29},
                    {"name": "Timbits", "price": 2.99}
                ],
                "min_price": 1.79,
                "max_price": 4.99,
                "days_of_operation": "Mon-Fri",
                "opening_hours": "08:00",
                "closing_hours": "16:00",
                "rating": 3.7
            },
            {
                "name": "True Eats",
                "description": "Health-focused counter with bowls, wraps, and fresh lighter meals.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "Chicken Power Bowl", "price": 11.99},
                    {"name": "Veggie Bowl", "price": 10.99},
                    {"name": "Avocado Toast", "price": 8.99},
                    {"name": "Protein Wrap", "price": 9.99},
                    {"name": "Kale Caesar Salad", "price": 9.49},
                    {"name": "Quinoa Bowl", "price": 10.49},
                    {"name": "Tofu Bowl", "price": 10.99},
                    {"name": "Smoothie", "price": 6.99},
                    {"name": "Greek Yogurt Cup", "price": 5.49},
                    {"name": "Chicken Caesar Wrap", "price": 10.49}
                ],
                "min_price": 5.49,
                "max_price": 11.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:00",
                "closing_hours": "19:00",
                "rating": 4.3
            },
            {
                "name": "Umi Sushi",
                "description": "Japanese spot serving sushi rolls, nigiri, bento, and sides.",
                "location": "MacEwan Student Centre",
                "image_url": "",
                "menu_items": [
                    {"name": "California Roll", "price": 6.99},
                    {"name": "Salmon Nigiri", "price": 7.99},
                    {"name": "Chicken Bento", "price": 12.99},
                    {"name": "Spicy Tuna Roll", "price": 7.99},
                    {"name": "Dynamite Roll", "price": 8.99},
                    {"name": "Tempura Roll", "price": 8.49},
                    {"name": "Avocado Roll", "price": 5.99},
                    {"name": "Salmon Sashimi", "price": 10.99},
                    {"name": "Shrimp Tempura", "price": 9.99},
                    {"name": "Miso Soup", "price": 2.99}
                ],
                "min_price": 2.99,
                "max_price": 12.99,
                "days_of_operation": "Daily",
                "opening_hours": "10:30",
                "closing_hours": "19:00",
                "rating": 4.4
            }
        ]

        for restaurant_data in restaurants:
            Restaurant.objects.create(**restaurant_data)

        self.stdout.write(
            self.style.SUCCESS(f"Successfully seeded {len(restaurants)} restaurants.")
        )